language: c

sudo: false

addons:
  apt:
    sources:
    - avsm
    packages:
    - ocaml
    - ocaml-native-compilers
    - opam

script: bash -ex .travis-ocaml.sh

env:
  - OCAML_VERSION=4.03.0
  - OCAML_VERSION=4.04.0
  - OCAML_VERSION=4.04.1
  - OCAML_VERSION=4.04.2
  - OCAML_VERSION=4.05.0
  - OCAML_VERSION=4.06.0
  - OCAML_VERSION=4.06.1
  - OCAML_VERSION=4.07.0
