language: c

sudo: required

script:
  - bash -ex .travis-ocaml.sh
  - bash -ex .run-test.sh

env:
  - OCAML_VERSION=4.03
  - OCAML_VERSION=4.04
  - OCAML_VERSION=4.05
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.07

os:
  - osx
  - linux
